// Table sourate → pages (générée depuis public/qcf-data/chapters.json).
// Utilisée par l'exercice « Numéro de page » pour calculer le rang d'une page
// à l'intérieur de sa sourate (ex. « la 12ème page de Al-Baqarah »).

export interface SurahPageInfo {
  nameArabic: string;
  nameSimple: string;
  startPage: number;
  endPage: number;
}

// Indexée par identifiant de sourate (1-114). L'index 0 est un remplissage.
export const SURAH_PAGES: Record<number, SurahPageInfo> = {
  1: { nameArabic: "الفاتحة", nameSimple: "Al-Fatihah", startPage: 1, endPage: 1 },
  2: { nameArabic: "البقرة", nameSimple: "Al-Baqarah", startPage: 2, endPage: 49 },
  3: { nameArabic: "آل عمران", nameSimple: "Ali 'Imran", startPage: 50, endPage: 76 },
  4: { nameArabic: "النساء", nameSimple: "An-Nisa", startPage: 77, endPage: 106 },
  5: { nameArabic: "المائدة", nameSimple: "Al-Ma'idah", startPage: 106, endPage: 127 },
  6: { nameArabic: "الأنعام", nameSimple: "Al-An'am", startPage: 128, endPage: 150 },
  7: { nameArabic: "الأعراف", nameSimple: "Al-A'raf", startPage: 151, endPage: 176 },
  8: { nameArabic: "الأنفال", nameSimple: "Al-Anfal", startPage: 177, endPage: 186 },
  9: { nameArabic: "التوبة", nameSimple: "At-Tawbah", startPage: 187, endPage: 207 },
  10: { nameArabic: "يونس", nameSimple: "Yunus", startPage: 208, endPage: 221 },
  11: { nameArabic: "هود", nameSimple: "Hud", startPage: 221, endPage: 235 },
  12: { nameArabic: "يوسف", nameSimple: "Yusuf", startPage: 235, endPage: 248 },
  13: { nameArabic: "الرعد", nameSimple: "Ar-Ra'd", startPage: 249, endPage: 255 },
  14: { nameArabic: "ابراهيم", nameSimple: "Ibrahim", startPage: 255, endPage: 261 },
  15: { nameArabic: "الحجر", nameSimple: "Al-Hijr", startPage: 262, endPage: 267 },
  16: { nameArabic: "النحل", nameSimple: "An-Nahl", startPage: 267, endPage: 281 },
  17: { nameArabic: "الإسراء", nameSimple: "Al-Isra", startPage: 282, endPage: 293 },
  18: { nameArabic: "الكهف", nameSimple: "Al-Kahf", startPage: 293, endPage: 304 },
  19: { nameArabic: "مريم", nameSimple: "Maryam", startPage: 305, endPage: 312 },
  20: { nameArabic: "طه", nameSimple: "Taha", startPage: 312, endPage: 321 },
  21: { nameArabic: "الأنبياء", nameSimple: "Al-Anbya", startPage: 322, endPage: 331 },
  22: { nameArabic: "الحج", nameSimple: "Al-Hajj", startPage: 332, endPage: 341 },
  23: { nameArabic: "المؤمنون", nameSimple: "Al-Mu'minun", startPage: 342, endPage: 349 },
  24: { nameArabic: "النور", nameSimple: "An-Nur", startPage: 350, endPage: 359 },
  25: { nameArabic: "الفرقان", nameSimple: "Al-Furqan", startPage: 359, endPage: 366 },
  26: { nameArabic: "الشعراء", nameSimple: "Ash-Shu'ara", startPage: 367, endPage: 376 },
  27: { nameArabic: "النمل", nameSimple: "An-Naml", startPage: 377, endPage: 385 },
  28: { nameArabic: "القصص", nameSimple: "Al-Qasas", startPage: 385, endPage: 396 },
  29: { nameArabic: "العنكبوت", nameSimple: "Al-'Ankabut", startPage: 396, endPage: 404 },
  30: { nameArabic: "الروم", nameSimple: "Ar-Rum", startPage: 404, endPage: 410 },
  31: { nameArabic: "لقمان", nameSimple: "Luqman", startPage: 411, endPage: 414 },
  32: { nameArabic: "السجدة", nameSimple: "As-Sajdah", startPage: 415, endPage: 417 },
  33: { nameArabic: "الأحزاب", nameSimple: "Al-Ahzab", startPage: 418, endPage: 427 },
  34: { nameArabic: "سبإ", nameSimple: "Saba", startPage: 428, endPage: 434 },
  35: { nameArabic: "فاطر", nameSimple: "Fatir", startPage: 434, endPage: 440 },
  36: { nameArabic: "يس", nameSimple: "Ya-Sin", startPage: 440, endPage: 445 },
  37: { nameArabic: "الصافات", nameSimple: "As-Saffat", startPage: 446, endPage: 452 },
  38: { nameArabic: "ص", nameSimple: "Sad", startPage: 453, endPage: 458 },
  39: { nameArabic: "الزمر", nameSimple: "Az-Zumar", startPage: 458, endPage: 467 },
  40: { nameArabic: "غافر", nameSimple: "Ghafir", startPage: 467, endPage: 476 },
  41: { nameArabic: "فصلت", nameSimple: "Fussilat", startPage: 477, endPage: 482 },
  42: { nameArabic: "الشورى", nameSimple: "Ash-Shuraa", startPage: 483, endPage: 489 },
  43: { nameArabic: "الزخرف", nameSimple: "Az-Zukhruf", startPage: 489, endPage: 495 },
  44: { nameArabic: "الدخان", nameSimple: "Ad-Dukhan", startPage: 496, endPage: 498 },
  45: { nameArabic: "الجاثية", nameSimple: "Al-Jathiyah", startPage: 499, endPage: 502 },
  46: { nameArabic: "الأحقاف", nameSimple: "Al-Ahqaf", startPage: 502, endPage: 506 },
  47: { nameArabic: "محمد", nameSimple: "Muhammad", startPage: 507, endPage: 510 },
  48: { nameArabic: "الفتح", nameSimple: "Al-Fath", startPage: 511, endPage: 515 },
  49: { nameArabic: "الحجرات", nameSimple: "Al-Hujurat", startPage: 515, endPage: 517 },
  50: { nameArabic: "ق", nameSimple: "Qaf", startPage: 518, endPage: 520 },
  51: { nameArabic: "الذاريات", nameSimple: "Adh-Dhariyat", startPage: 520, endPage: 523 },
  52: { nameArabic: "الطور", nameSimple: "At-Tur", startPage: 523, endPage: 525 },
  53: { nameArabic: "النجم", nameSimple: "An-Najm", startPage: 526, endPage: 528 },
  54: { nameArabic: "القمر", nameSimple: "Al-Qamar", startPage: 528, endPage: 531 },
  55: { nameArabic: "الرحمن", nameSimple: "Ar-Rahman", startPage: 531, endPage: 534 },
  56: { nameArabic: "الواقعة", nameSimple: "Al-Waqi'ah", startPage: 534, endPage: 537 },
  57: { nameArabic: "الحديد", nameSimple: "Al-Hadid", startPage: 537, endPage: 541 },
  58: { nameArabic: "المجادلة", nameSimple: "Al-Mujadila", startPage: 542, endPage: 545 },
  59: { nameArabic: "الحشر", nameSimple: "Al-Hashr", startPage: 545, endPage: 548 },
  60: { nameArabic: "الممتحنة", nameSimple: "Al-Mumtahanah", startPage: 549, endPage: 551 },
  61: { nameArabic: "الصف", nameSimple: "As-Saf", startPage: 551, endPage: 552 },
  62: { nameArabic: "الجمعة", nameSimple: "Al-Jumu'ah", startPage: 553, endPage: 554 },
  63: { nameArabic: "المنافقون", nameSimple: "Al-Munafiqun", startPage: 554, endPage: 555 },
  64: { nameArabic: "التغابن", nameSimple: "At-Taghabun", startPage: 556, endPage: 557 },
  65: { nameArabic: "الطلاق", nameSimple: "At-Talaq", startPage: 558, endPage: 559 },
  66: { nameArabic: "التحريم", nameSimple: "At-Tahrim", startPage: 560, endPage: 561 },
  67: { nameArabic: "الملك", nameSimple: "Al-Mulk", startPage: 562, endPage: 564 },
  68: { nameArabic: "القلم", nameSimple: "Al-Qalam", startPage: 564, endPage: 566 },
  69: { nameArabic: "الحاقة", nameSimple: "Al-Haqqah", startPage: 566, endPage: 568 },
  70: { nameArabic: "المعارج", nameSimple: "Al-Ma'arij", startPage: 568, endPage: 570 },
  71: { nameArabic: "نوح", nameSimple: "Nuh", startPage: 570, endPage: 571 },
  72: { nameArabic: "الجن", nameSimple: "Al-Jinn", startPage: 572, endPage: 573 },
  73: { nameArabic: "المزمل", nameSimple: "Al-Muzzammil", startPage: 574, endPage: 575 },
  74: { nameArabic: "المدثر", nameSimple: "Al-Muddaththir", startPage: 575, endPage: 577 },
  75: { nameArabic: "القيامة", nameSimple: "Al-Qiyamah", startPage: 577, endPage: 578 },
  76: { nameArabic: "الانسان", nameSimple: "Al-Insan", startPage: 578, endPage: 580 },
  77: { nameArabic: "المرسلات", nameSimple: "Al-Mursalat", startPage: 580, endPage: 581 },
  78: { nameArabic: "النبإ", nameSimple: "An-Naba", startPage: 582, endPage: 583 },
  79: { nameArabic: "النازعات", nameSimple: "An-Nazi'at", startPage: 583, endPage: 584 },
  80: { nameArabic: "عبس", nameSimple: "'Abasa", startPage: 585, endPage: 585 },
  81: { nameArabic: "التكوير", nameSimple: "At-Takwir", startPage: 586, endPage: 586 },
  82: { nameArabic: "الإنفطار", nameSimple: "Al-Infitar", startPage: 587, endPage: 587 },
  83: { nameArabic: "المطففين", nameSimple: "Al-Mutaffifin", startPage: 587, endPage: 589 },
  84: { nameArabic: "الإنشقاق", nameSimple: "Al-Inshiqaq", startPage: 589, endPage: 589 },
  85: { nameArabic: "البروج", nameSimple: "Al-Buruj", startPage: 590, endPage: 590 },
  86: { nameArabic: "الطارق", nameSimple: "At-Tariq", startPage: 591, endPage: 591 },
  87: { nameArabic: "الأعلى", nameSimple: "Al-A'la", startPage: 591, endPage: 592 },
  88: { nameArabic: "الغاشية", nameSimple: "Al-Ghashiyah", startPage: 592, endPage: 592 },
  89: { nameArabic: "الفجر", nameSimple: "Al-Fajr", startPage: 593, endPage: 594 },
  90: { nameArabic: "البلد", nameSimple: "Al-Balad", startPage: 594, endPage: 594 },
  91: { nameArabic: "الشمس", nameSimple: "Ash-Shams", startPage: 595, endPage: 595 },
  92: { nameArabic: "الليل", nameSimple: "Al-Layl", startPage: 595, endPage: 596 },
  93: { nameArabic: "الضحى", nameSimple: "Ad-Duhaa", startPage: 596, endPage: 596 },
  94: { nameArabic: "الشرح", nameSimple: "Ash-Sharh", startPage: 596, endPage: 596 },
  95: { nameArabic: "التين", nameSimple: "At-Tin", startPage: 597, endPage: 597 },
  96: { nameArabic: "العلق", nameSimple: "Al-'Alaq", startPage: 597, endPage: 597 },
  97: { nameArabic: "القدر", nameSimple: "Al-Qadr", startPage: 598, endPage: 598 },
  98: { nameArabic: "البينة", nameSimple: "Al-Bayyinah", startPage: 598, endPage: 599 },
  99: { nameArabic: "الزلزلة", nameSimple: "Az-Zalzalah", startPage: 599, endPage: 599 },
  100: { nameArabic: "العاديات", nameSimple: "Al-'Adiyat", startPage: 599, endPage: 600 },
  101: { nameArabic: "القارعة", nameSimple: "Al-Qari'ah", startPage: 600, endPage: 600 },
  102: { nameArabic: "التكاثر", nameSimple: "At-Takathur", startPage: 600, endPage: 600 },
  103: { nameArabic: "العصر", nameSimple: "Al-'Asr", startPage: 601, endPage: 601 },
  104: { nameArabic: "الهمزة", nameSimple: "Al-Humazah", startPage: 601, endPage: 601 },
  105: { nameArabic: "الفيل", nameSimple: "Al-Fil", startPage: 601, endPage: 601 },
  106: { nameArabic: "قريش", nameSimple: "Quraysh", startPage: 602, endPage: 602 },
  107: { nameArabic: "الماعون", nameSimple: "Al-Ma'un", startPage: 602, endPage: 602 },
  108: { nameArabic: "الكوثر", nameSimple: "Al-Kawthar", startPage: 602, endPage: 602 },
  109: { nameArabic: "الكافرون", nameSimple: "Al-Kafirun", startPage: 603, endPage: 603 },
  110: { nameArabic: "النصر", nameSimple: "An-Nasr", startPage: 603, endPage: 603 },
  111: { nameArabic: "المسد", nameSimple: "Al-Masad", startPage: 603, endPage: 603 },
  112: { nameArabic: "الإخلاص", nameSimple: "Al-Ikhlas", startPage: 604, endPage: 604 },
  113: { nameArabic: "الفلق", nameSimple: "Al-Falaq", startPage: 604, endPage: 604 },
  114: { nameArabic: "الناس", nameSimple: "An-Nas", startPage: 604, endPage: 604 },
};

/** Renvoie les infos de pagination d'une sourate, ou null si inconnue. */
export function getSurahPageInfo(surah: number): SurahPageInfo | null {
  return SURAH_PAGES[surah] ?? null;
}
